spring:
  config:
    name: project2
  datasource:
    url: jdbc:postgresql://localhost:5432/Spring
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Изменено с create-drop на update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  port: 8080